service: API-user
frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128
  region: us-east-1
  stage: ${opt:stage, 'dev'}

functions:
  creteUser:
    handler: src/handlers/createUser.handler
    events:
      - httpApi:
          path: /users
          method: POST

  getAll:
    handler: src/handlers/getAllUsers.handler
    events:
      - httpApi:
          path: /users
          method: GET

  getUser:
    handler: src/handlers/getUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: GET

  deleteUser:
    handler: src/handlers/deleteUser.handler
    events:
      - httpApi:
          path: /users/{id}
          method: DELETE

  updateUser:
    handler: src/handlers/updateUser.handler
    events:
      - httpApi:
          path: /users
          method: PATCH
